import type { Metadata } from "next";
import Link from "next/link";

const localDataPoints = [
  {
    title: "Notes, drafts, and attachments",
    description:
      "Your written content lives entirely inside your browser using IndexedDB. No background sync or remote storage is performed.",
  },
  {
    title: "Chunks and embeddings",
    description:
      "Semantic-search chunks and the vectors generated by on-device transformers are stored locally. If you opt into remote fallback, only the chunk text needed for that request is sent upstream for embedding and the resulting vector immediately returns to IndexedDB.",
  },
  {
    title: "Preferences and caches",
    description:
      "Theme selection, feature flags, and model caches are kept in local storage APIs to preserve your experience offline.",
  },
] as const;

const aiDisclosures = [
  {
    title: "Explicit AI requests only",
    description:
      "When you trigger an AI action (e.g., Ask Mnemos or Summarize), the specific text you submit is sent to the configured server-side model so it can respond.",
  },
  {
    title: "No surprise uploads",
    description:
      "Mnemos never uploads your notes or embeddings automatically. Each outbound call clearly indicates the payload before it leaves your device.",
  },
  {
    title: "Prompted embedding fallback",
    description:
      "If your device cannot run the local embedding model, the app pauses the action and asks whether you want to fall back to remote embedding generation before any text is transmitted.",
  },
  {
    title: "Network visibility",
    description:
      "All remote requests use HTTPS and can be inspected via your browser's network panel for full transparency.",
  },
] as const;

const userControls = [
  {
    title: "Delete data at any time",
    description:
      "Use your browser's storage controls to clear IndexedDB/localStorage or delete notes individually inside the app.",
  },
  {
    title: "Operate fully offline",
    description:
      "Mnemos remains functional without connectivity, preventing accidental data transfer and letting you audit network usage yourself.",
  },
  {
    title: "Auditability",
    description:
      "The entire codebase is open-source, so you can verify the storage model or run your own build.",
  },
] as const;

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "Learn how Mnemos handles, stores, and protects your notes.",
};

export default function PrivacyPage() {
  return (
    <div className="relative pb-32">
      <main className="mx-auto max-w-4xl space-y-12 px-6 py-16">
        <header className="space-y-4">
          <p className="text-muted-foreground text-xs font-semibold tracking-[0.4em] uppercase">
            Privacy Policy
          </p>
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <h1 className="text-foreground text-3xl font-semibold tracking-tight">
              Your notes stay on your device
            </h1>
            <Link
              href="/"
              className="text-primary hover:text-primary/80 text-sm font-medium"
            >
              ← Back to Mnemos
            </Link>
          </div>
          <p className="text-muted-foreground text-base leading-relaxed">
            Mnemos is built as a privacy-first, local-first notebook. This page
            explains what data is created, where it lives, and the limited cases
            where it can leave your browser.
          </p>
          <p className="text-muted-foreground text-sm">
            Last updated: December 25, 2025
          </p>
        </header>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">Data stored locally</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            Everything below is stored directly on your device using
            IndexedDB/localStorage. Mnemos does not transmit these assets unless
            you explicitly export them or opt into the remote embedding fallback
            described below.
          </p>
          <ul className="grid gap-4 md:grid-cols-2">
            {localDataPoints.map((item) => (
              <li
                key={item.title}
                className="border-border/60 bg-muted/30 rounded-2xl border p-4"
              >
                <h3 className="text-base font-semibold">{item.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {item.description}
                </p>
              </li>
            ))}
          </ul>
          <p className="text-muted-foreground text-xs leading-relaxed">
            Implementation detail: when fallback is enabled, Mnemos posts the
            affected chunk text and IDs to the server-side embed action in
            src/server-actions/embed.ts only long enough to generate vectors,
            then stores the returned embeddings back in IndexedDB.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">
            When data leaves your device
          </h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            Mnemos only contacts remote services when you explicitly request an
            AI-powered operation. Those calls are limited to the text you send
            and the metadata needed to fulfill the request. If your hardware
            cannot run local embeddings, Mnemos pauses the workflow and asks
            whether you want to enable remote embedding generation before
            anything leaves the device.
          </p>
          <ul className="space-y-3">
            {aiDisclosures.map((item) => (
              <li
                key={item.title}
                className="border-border/60 rounded-2xl border p-4"
              >
                <h3 className="text-base font-semibold">{item.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {item.description}
                </p>
              </li>
            ))}
          </ul>
          <div className="text-muted-foreground text-sm leading-relaxed">
            <p>
              Mnemos does not collect analytics, advertising identifiers, or
              tracking cookies. If you self-host or point AI calls to a third
              party, their policies will govern the transmitted data.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">Your controls</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            You decide when and how your information is retained.
          </p>
          <ul className="grid gap-4 md:grid-cols-3">
            {userControls.map((item) => (
              <li key={item.title} className="rounded-2xl border p-4">
                <h3 className="text-base font-semibold">{item.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">
                  {item.description}
                </p>
              </li>
            ))}
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">{"Children's privacy"}</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            Mnemos is designed for adult productivity use and is not intended
            for children under 13. If you are a parent or guardian and believe a
            child has provided data, you can clear the browser storage or reach
            out for help below.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold">Contact</h2>
          <p className="text-muted-foreground text-sm leading-relaxed">
            Questions or requests? Open an issue on the{" "}
            <a
              href="https://github.com/brunocpf/mnemos"
              target="_blank"
              rel="noreferrer"
              className="text-primary hover:text-primary/80 font-medium"
            >
              GitHub repository
            </a>{" "}
            or reach the maintainers via the channels listed in the README.
          </p>
        </section>
      </main>
    </div>
  );
}
