/* eslint-disable @next/next/no-head-element */
import type { Metadata } from "next";
import { Figtree } from "next/font/google";

import { OnboardingGate } from "@/components/onboarding-gate";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { EmbedderProvider } from "@/providers/embedder-provider";

import "./globals.css";

const fontSans = Figtree({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fontSans.variable} suppressHydrationWarning>
      <head />
      <body className="antialiased">
        <EmbedderProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <OnboardingGate>{children}</OnboardingGate>
            <Toaster />
          </ThemeProvider>
        </EmbedderProvider>
      </body>
    </html>
  );
}
