import type { Metadata, Viewport } from "next";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { Figtree } from "next/font/google";
import { notFound } from "next/navigation";

import { AppFooter } from "@/components/app-footer";
import { AppHeader } from "@/components/app-header";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { routing } from "@/i18n/routing";
import { EmbedderProvider } from "@/providers/embedder-provider";
import { HistoryProvider } from "@/providers/history-provider";
import { SearchValueProvider } from "@/providers/search-value-provider";
import { SettingsProvider } from "@/providers/settings-provider";
import { SummarizerProvider } from "@/providers/summarizer-provider";

import "./globals.css";

const font = Figtree({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
  interactiveWidget: "resizes-visual",
  viewportFit: "cover",
};

export default async function RootLayout({
  children,
  params,
}: LayoutProps<"/[locale]">) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <html
      className={`h-dvh snap-none overflow-y-auto scroll-smooth focus-within:snap-none ${font.variable}`}
      lang={locale}
      suppressHydrationWarning
      data-scroll-behavior="smooth"
    >
      <head />
      <body className="antialiased">
        <NextIntlClientProvider>
          <HistoryProvider>
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
              <SettingsProvider>
                <EmbedderProvider>
                  <SummarizerProvider>
                    <SearchValueProvider>
                      <AppHeader />
                      {children}
                      <AppFooter />
                      <Toaster />
                    </SearchValueProvider>
                  </SummarizerProvider>
                </EmbedderProvider>
              </SettingsProvider>
            </ThemeProvider>
          </HistoryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
